import "~/styles/globals.css";

import { type Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/dashboard/Sidebar";
import Topbar from "~/components/dashboard/Topbar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Providers>
          <AppSidebar />
          <main className="flex h-screen w-full flex-col">
            <div className="bg-background flex w-full py-4">
              <Topbar />
            </div>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
